DELIMITER //
CREATE PROCEDURE `PROC_NEW_POLINE_G4`(IN inPoNoG4 INT(11), IN inPartNoG4 INT(11), IN inQtyG4 INT(11))
BEGIN
    DECLARE PRICE DECIMAL(19,4);
	-- CALCULATE THE LINE PRICE FOR THE PART QUANTITY
	SELECT currentPriceG4 INTO PRICE FROM PartsG4 WHERE partNoG4=inPartNoG4;
	-- CREATE A NEW PO LINE USING THE PROVIDED INFO.
	INSERT INTO POLinesG4 (poNoG4, partNoG4, linePriceG4, qtyG4) VALUES (inPoNoG4, inPartNoG4, (PRICE * inQtyG4), inQtyG4);
END //
DELIMITER ;