DELIMITER //
CREATE PROCEDURE `PROC_NEW_PO_G4`(IN inClientCompIdG4 INT(11))
BEGIN
	-- INSERT A NEW PO INTO THE POG4 TABLE.
	INSERT INTO POsG4 (clientCompIdG4) VALUES (inClientCompIdG4);
	-- RETURN THE NEW PO ID OF THE NEWLY CREATED POsG4 RECORD ABOVE.
    SELECT LAST_INSERT_ID() AS NEW_ID;
END //
DELIMITER ;