DELIMITER //
CREATE PROCEDURE PROC_PART_REORDER_G4(IN inPartNoG4 INT(11))
BEGIN
	DECLARE CURR_QTY INT;
	DECLARE MIN_QTY INT;
	SELECT qtyG4 INTO CURR_QTY FROM PartsG4 WHERE partNoG4 = inPartNoG4;
	SELECT minQtyG4 INTO MIN_QTY FROM PartsG4 WHERE partNoG4 = inPartNoG4;
   	IF (CURR_QTY < MIN_QTY) THEN 
		-- MARK THE PART TO BE REORDERED SINCE THE CURRENT QUANTY IS BELOW THE MANDATORY THRESHOLD.
		UPDATE PartsG4 SET reorderG4 = 1 WHERE partNoG4 = inPartNoG4;
	ELSE
		-- MARK THE PART NOT TO BE REORDERED.
		UPDATE PartsG4 SET reorderG4 = 0 WHERE partNoG4 = inPartNoG4;
	END IF;
END //
DELIMITER ;