DELIMITER //
CREATE PROCEDURE PROC_CLIENT_PAYMENT_G4(IN inPoNoG4 INT(11), IN inClientCompIdG4 INT(11), IN inAmountPaidG4 DECIMAL(19,4))
BEGIN
	DECLARE COUNT_LINES INT;
	DECLARE SUM_LINEPRICE DECIMAL(19,4);
	DECLARE SUM_ALREADY_PAID DECIMAL(19,4);
	-- DEFINE AN ERROR HANDLING. FIRST ROLLBACK THEN RETHROW THE ERROR TO THE REQUESTOR APPLICATION.
    DECLARE EXIT HANDLER FOR SQLEXCEPTION, SQLWARNING, NOT FOUND
    BEGIN
		ROLLBACK;
        RESIGNAL;
	END;	
	START TRANSACTION;
	-- RETRIEVE THE TOTAL PRICE.
	SELECT COUNT(*) INTO COUNT_LINES 
		FROM POsG4 INNER JOIN POLinesG4 USING(poNoG4) WHERE POsG4.poNoG4 = inPoNoG4 AND POsG4.clientCompIdG4 = inClientCompIdG4;
	SELECT SUM(linePriceG4) INTO SUM_LINEPRICE 
		FROM POsG4 INNER JOIN POLinesG4 USING(poNoG4) WHERE POsG4.poNoG4 = inPoNoG4 AND POsG4.clientCompIdG4 = inClientCompIdG4;
	IF (COUNT_LINES <= 0) THEN
		-- USER DEFINED ERROR (NO SUCH PO EXISTS FOR THE CLIENT).
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT='No product order exists for the given PO number and client Id.';
	ELSEIF (SUM_LINEPRICE <> inAmountPaidG4) THEN -- FOR NOW, WE ONLY TAKE ONE TIME PAYMENT FOR THE TOTAL PRICE FOR ONE PO.
		-- USER DEFINED ERROR (PAID AMOUNT DOES NOT MATCH THE TOTAL PRICE OF PO).
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT='The payment amount is not accurate for the cost of the product order.';
	ELSE
		-- CHECK IF THE PO HAS BEEN ALREADY PAID (ONLY POSITIVE AMOUNT PAID ARE TAKEN INTO CONSIDERATION).
		SELECT SUM(amountPaidG4) INTO SUM_ALREADY_PAID FROM PaymentG4 WHERE (poNoG4=inPoNoG4) AND (amountPaidG4 > 0);
		IF SUM_ALREADY_PAID >= SUM_LINEPRICE THEN
			-- USER DEFINED ERROR ().
			SIGNAL SQLSTATE '45000'
			SET MESSAGE_TEXT='The product order has been already paid.';
		END IF;
		-- TAKE THE PAYMENT.
		-- (1) RECORD THE PAYMENT IN THE PaymentG4 TABLE.
        INSERT INTO PaymentG4 (poNoG4, amountPaidG4) VALUES (inPoNoG4, inAmountPaidG4);
        
		-- (2) CHANGE THE PO STATUS TO 2 (= PAID).
        UPDATE POsG4 SET statusG4 = 2 WHERE POsG4.poNoG4 = inPoNoG4;
        
		-- (3) DEDUCT THE PAID AMOUNT FROM moneyOwedG4 IN THE ClientG4 TABLE.
		UPDATE ClientG4 SET moneyOwedG4 = (moneyOwedG4 - inAmountPaidG4) WHERE clientCompIdG4=inClientCompIdG4;
		
		-- (4) SEND A SUCCESS MESSAGE.
        SELECT 'SUCCESSFULLY PROCESSED.';
        
	END IF;
	COMMIT;
END //
DELIMITER ;

