DELIMITER //
CREATE TRIGGER TRG_AFTER_POLINE_UPDATE_G4
AFTER
UPDATE ON POLinesG4
FOR EACH ROW
BEGIN
	-- WHENEVER AFTER THE POLinesG4 TABLE IS UPDATED, UPDATE THE RE-ORDER FLAG (TRUE/FALSE) IN THE PartsG4 TABLE 
    	-- BY INVOKING A DEDICATED TRIGGER COMPARING THE CURRENT VALUES OF THE qtyG4 AND THE minQtyG4 AND UPDATE THE REORDER FLAG.
	CALL PROC_PART_REORDER_G4(NEW.partNoG4);
END  //
DELIMITER ;
